id = "amber"
name = "Amber"
description = "Amber Language support."
version = "0.3.3"
schema_version = 1
authors = ["Paweł Karaś <pkaras.it@gmail.com>", "Hubert Jabłoński <hubik080@gmail.com>"]
repository = "https://github.com/amber-lang/amber-zed"

[grammars.amber]
repository = "https://github.com/amber-lang/tree-sitter-amber"
commit = "107c6d4a420fb0c5962b62ebd9347b7eb0015957"

[language_servers.amber]
name = "Amber Language Server"
language = "Amber"
